"use client";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
export function AuthForm({ mode }: { mode:"login"|"signup" }) { const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [loading,setLoading]=useState(false); const router=useRouter(); const signup=mode==="signup";
 async function submit(formData:FormData){setLoading(true);setError("");setNotice(""); const supabase=createClient(); const email=String(formData.get("email")||""); const password=String(formData.get("password")||""); if(signup){const fullName=String(formData.get("fullName")||""); const {error}=await supabase.auth.signUp({email,password,options:{data:{full_name:fullName},emailRedirectTo:`${location.origin}/dashboard`}}); if(error)setError(error.message); else setNotice("Check your email to confirm your account, then return here to sign in.");}else{const {error}=await supabase.auth.signInWithPassword({email,password}); if(error)setError(error.message); else router.push("/dashboard");}setLoading(false)}
 return <form action={submit} className="space-y-4">{signup&&<Field name="fullName" label="Full name" autoComplete="name" required/>}<Field name="email" label="Email address" type="email" autoComplete="email" required/><Field name="password" label="Password" type="password" autoComplete={signup?"new-password":"current-password"} minLength={8} required/>{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice&&<p role="status" className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}<button disabled={loading} className="btn-primary w-full">{loading?"Please wait…":signup?"Create account":"Sign in"}</button>{!signup&&<Link className="block text-center text-sm font-medium text-brand-700 hover:underline" href="/forgot-password">Forgot password?</Link>}<p className="text-center text-sm text-slate-600">{signup?"Already a member? ":"New to AlumniConnect? "}<Link className="font-semibold text-brand-700 hover:underline" href={signup?"/login":"/signup"}>{signup?"Sign in":"Create an account"}</Link></p></form> }
function Field({label,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){return <label className="block"><span className="label">{label}</span><input className="input" {...props}/></label>}
