"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import type { Profile } from "@/types/database";

export function ProfileForm({ profile }: { profile: Profile }) {
  const [error, setError] = useState(""); const [saved, setSaved] = useState(false); const [loading, setLoading] = useState(false);
  const [avatarUrl, setAvatarUrl] = useState(profile.avatar_url || ""); const router = useRouter();
  async function uploadAvatar(file: File) { setError(""); if (file.size > 5 * 1024 * 1024) return setError("Choose an image smaller than 5 MB."); const path = `${profile.id}/avatar.${file.name.split(".").pop() || "jpg"}`; const supabase = createClient(); const { error } = await supabase.storage.from("avatars").upload(path, file, { upsert: true }); if (error) return setError(error.message); setAvatarUrl(supabase.storage.from("avatars").getPublicUrl(path).data.publicUrl); }
  async function submit(data: FormData) { setLoading(true); setError(""); setSaved(false); const value = (key:string) => String(data.get(key)||""); const payload = { full_name:value("full_name").trim(), graduation_year:value("graduation_year")?Number(value("graduation_year")):null, department:value("department")||null, location:value("location")||null, current_company:value("current_company")||null, job_title:value("job_title")||null, industry:value("industry")||null, bio:value("bio")||null, linkedin_url:value("linkedin_url")||null, avatar_url:avatarUrl||null, visibility:value("visibility") }; const { error } = await createClient().from("profiles").update(payload).eq("id",profile.id); if(error)setError(error.message); else {setSaved(true);router.refresh()} setLoading(false); }
  const fields = [["full_name","Full name","text"],["graduation_year","Graduation year","number"],["department","Department","text"],["location","Location","text"],["current_company","Current company","text"],["job_title","Job title","text"],["industry","Industry","text"],["linkedin_url","LinkedIn URL","url"]] as const;
  return <form action={submit} className="card grid gap-5 md:grid-cols-2">{fields.map(([name,label,type])=><label key={name} className="block"><span className="label">{label}</span><input className="input" name={name} type={type} defaultValue={String(profile[name]??"")} required={name==="full_name"}/></label>)}<label className="block"><span className="label">Profile photo</span><input className="input" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>e.target.files?.[0]&&uploadAvatar(e.target.files[0])}/><span className="mt-1 block text-xs text-slate-500">PNG, JPG, or WebP; up to 5 MB.</span></label>{avatarUrl&&<img src={avatarUrl} alt="Current profile" className="h-20 w-20 rounded-full object-cover"/>}<label className="block md:col-span-2"><span className="label">About you</span><textarea className="input min-h-28" name="bio" maxLength={1000} defaultValue={profile.bio??""}/><span className="mt-1 block text-xs text-slate-500">Up to 1,000 characters.</span></label><label className="block"><span className="label">Profile visibility</span><select className="input" name="visibility" defaultValue={profile.visibility}><option value="public">Public — visible to anyone</option><option value="directory">Directory — visible to signed-in members</option><option value="private">Private — only me and admins</option></select></label>{error&&<p role="alert" className="text-sm text-red-700 md:col-span-2">{error}</p>}{saved&&<p role="status" className="text-sm text-emerald-700 md:col-span-2">Profile saved.</p>}<div className="md:col-span-2"><button disabled={loading} className="btn-primary">{loading?"Saving…":"Save profile"}</button></div></form>;
}
